# Finding necessary resources

With the help of the camera system, dr. Elena Vasilescu has managed to identify a very important package that dropped on the surface during the failed landing. If her calculations are correct, the package contains enough food supplies to last for a year, by which time she hopes to be either out of Mars, or have received help from Earth. The camera system reports that the package is located in the following coordinates: $X = -40 m$, $Y = -90 m$, and $Z = 200 m$. The coordinate frame of the box is rotated around the X axis of the camera by -90 degrees. These coordinates are relative to the camera. 

<img src="../artwork/stranded/mars_base_isometric_annotated.png" width=90%/>

She can only perform a short trip around the base, using one of the rovers that is equipped with a crane. That is why she needs to identify the location of the package accurately, so she can save time and reduce the risk of getting stranded out of the base.

After checking the operations manual from the mission, dr. Vasilescu has determined that the camera system is located at $X = 54m$, $ Y = 220 m$, and $Z= 90 m$ away from her, and is rotated around her Z axis by 180 degrees, and around her X axis by 90 degrees.

Can you help her find the location of the package relative to her base?

What maneuvers does she need to perform with her crane to go from her base location to the box. The crane must be aligned with the coordinate system of the box in order to pick it up.

## Expand for help

* Calculate the transformation from frame $V$ to frame $C$ as $R_V^C$
* Transform the coordinates of the box $B$ from the frame of the camera $C$ ($B_C$) to the coordinates of the box on the frame of dr. Vasilescu ($P_V$) using equation 1.11

In [22]:
from ipywidgets import interact, widgets
from spatialmath.base import *
import numpy as np

xv = -40
yv = -90
zv = 200
xc = 54
yc = -220
zc = 90


Tpc = transl(xv, yv, zv)@trotx(-90, 'deg')
print(Tpc)
# calculate the transformation from frame V to frame C as Rvc
Tcv = transl(xc, yc, zc)@trotz(180, 'deg')@trotx(90, 'deg')
print(Tcv)

#package with respect to vasilescu
print(Tcv@Tpc)

[[ 1.000000e+00  0.000000e+00  0.000000e+00 -4.000000e+01]
 [ 0.000000e+00  6.123234e-17  1.000000e+00 -9.000000e+01]
 [ 0.000000e+00 -1.000000e+00  6.123234e-17  2.000000e+02]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
[[-1.00000000e+00 -7.49879891e-33  1.22464680e-16  5.40000000e+01]
 [ 1.22464680e-16 -6.12323400e-17  1.00000000e+00  2.20000000e+02]
 [ 0.00000000e+00  1.00000000e+00  6.12323400e-17  9.00000000e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-1.00000000e+00 -7.49879891e-33  1.22464680e-16  1.40000000e+01]
 [ 7.49879891e-33  1.00000000e+00  1.22464680e-16  1.42108547e-14]
 [-1.22464680e-16  1.22464680e-16 -1.00000000e+00 -2.00000000e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


# Back at home

With the help of your instructor, connect to the robot arm on your desk and execute the cell below. Move around the sliders to get familiar with how the robot moves. Make sure you read the instructions on the desk, and keep them in mind. Robots can be dangerous, so let's be friendly with them ;)

In [1]:
### Cell for sending commands to the AL5D robot ###
# Importing necessary modules
from al5d_control import *
from ipywidgets import interact, fixed

rrob = AL5DControl()
interact(rrob.robot_control, q0=(-90,90), q1=(-90,90), q2=(-90,90), q3=(-90,90), q4=(-90,90), gripper=(-90,90), dq0=fixed(15),dq1=fixed(15),dq2=fixed(15),dq3=fixed(15), dq4=fixed(15), vel=fixed(False)) 

ModuleNotFoundError: No module named 'al5d_control'