# Helping dr. Vasilescu

As you saw in the previous laboratory, the MARS-O-HELP robot has the same kinematic structure as the AL5D robot manipulator you have on your desk. You can review its structure in the figure below.
    
   <center>
        <figure>
          <img src="../artwork/fkine/al5d.png"  width=40%/>
        </figure>
        <figure>
          <img src="../artwork/DH/AL5D_mdw.png"  width=50%/>
          <figcaption>AL5D robot and its schematic</figcaption>
        </figure>
        
   </center>
   
After the MARS-O-HELP picked up the liquid nitrogen container, it has the following set of joint coordinates.

$ q= \begin{bmatrix} \pi/6 & -\pi/6 & \pi/8 & 0 & 0 \end{bmatrix} $ [rad]

    a. Calculate the Jacobian of the AL5D model for the above set of joint coordinates, given the transformation matrices for each link (next cell)
    b. Create the AL5D model from the robotic toolbox
    c. Calculate the Jacobian for the same sets of joint coordinates below using the robotics toolbox.
    d. Compare the results with your Jacobian for the same joint coordinates.
    e. Calculate the resulting end-effector velocities (linear and angular) for this set of joint coordinates and joint velocities equal to:

$ \dot{q} = \begin{bmatrix} 0.1 & 0.14 & 0.1. & 0.02 & 0.1  \end{bmatrix} $ [rad/s]

    f. Dr. Vasilescu needs to move the robot with a specific velocity along the Y-axis (0.2 m/s). The robot should not move in any other direction. What are the joint velocities required to achieve this motion.

The transformation matrices for the AL5D robot stored in list `R`. The first element represents $R_0^1$, the second $R_0^2$, and the nth element $R_0^n$. You need to update variable `q` for the desired joint coordinates.

In [84]:
import roboticstoolbox as rtb
import spatialmath.base.symbolic as sym
from spatialmath.base import trotx, trotz, transl
from spatialmath import SE3
import numpy as np
from sympy import *
init_printing(num_columns=500)

al5d = rtb.models.DH.AL5D_mdw() # create the AL5D model 

# initialisations
pR = sym.symbol("R_0^1:7")
T = np.eye(4)
R = []

# loop for saving and printing the transformation matrices from the base to joint i in variable R
q = np.array([np.pi/6, -np.pi/6, np.pi/8, 0, 0])

# Calculate the Jacobian of the AL5D model for the above set of joint coordinates given the transformation matrices for each link (next cell)
J = rob.jacob0(q)
print("Jacobian of the AL5D model: \n", J)

for i in [0,1,2,3,4]:   
    display(pR[i])
    T = T@rob.links[i].A(q[i]).A
    R.append(T)
    pprint(Matrix(R[i]))
    
display(pR[5])
R.append(T*rob.tool)
pprint(Matrix(T*rob.tool))

# Calculate the Jacobian for the same sets of joint coordinates below using the robotics toolbox.
z = []
o = []
o_n = R[5][:-1,-1]
J_v = []
J_w = []
J = []
for i in range(5):
    z.append(R[i][:-1,0])
    o.append(R[i][:-1,i-1])
    J_v.append(np.cross(z[i], o_n - o[i]).reshape(3,1))
    J_w.append(z[i].reshape(3,1))
    J.append(np.concatenate((J_v[i], J_w[i]),axis = 0))
    
display("Jacobian for the same sets of joint coordinates: ")
pprint(J)

# Calculate the resulting end-effector velocities (linear and angular) for the set of joint coordinates and joint velocities below
q_dot = [0.1, 0.14, 0.1, 0.02, 0.1]
ksi = J@q_dot
display("End-effector velocities for the given set of joint coordinates and joint velocities: ")
pprint(ksi)

# Dr. Vasilescu needs to move the robot with a specific velocity along the Y-axis (0.2 m/s). The robot should not move in any other direction. What are the joint velocities required to achieve this motion.
q_double_dot = np.pinv(J) * ksi
display("Joint velocities needed to acheive this motion: ")
pprint(q_double_dot)

Jacobian of the AL5D model: 
 [[-0.103293114803349 0.0215564517100815 -0.130180771325968
  0.00803796345422570 0]
 [-0.164468922911445 -0.0124456231975887 0.0751599033683610
  -0.00464072036403358 0]
 [0 0.196080822776050 -0.122674520930449 0.00712189995797302 0]
 [5.55111512312578e-17 -0.500000000000000 0.500000000000000
  -0.500000000000000 -0.527202862365669]
 [2.77555756156289e-17 -0.866025403784439 0.866025403784439
  -0.866025403784439 0.304380714504360]
 [-1.00000000000000 0 0 0 0.793353340291235]]


⎡-0.866025403784439         0.5          0       0   ⎤
⎢                                                    ⎥
⎢       0.5          0.866025403784439   0       0   ⎥
⎢                                                    ⎥
⎢        0                   0          -1.0  0.06858⎥
⎢                                                    ⎥
⎣        0                   0           0      1.0  ⎦


⎡0.437430139655675   -0.747432186168629         -0.5         -0.00173205080756888⎤
⎢                                                                                ⎥
⎢-0.252550408881859  0.431530173885449   -0.866025403784439         0.001        ⎥
⎢                                                                                ⎥
⎢0.863060347770897   0.505100817763719           0                 0.06858       ⎥
⎢                                                                                ⎥
⎣        0                   0                   0                   1.0         ⎦


⎡0.548848270915586   -0.669899675707469         0.5         0.0614546713885903 ⎤
⎢                                                                              ⎥
⎢-0.316877696957374   0.38676675809975   0.866025403784439  -0.0363699904837146⎥
⎢                                                                              ⎥
⎢ -0.7735335161995   -0.633755393914748          0           0.194008560341545 ⎥
⎢                                                                              ⎥
⎣        0                   0                   0                  1.0        ⎦


⎡ 0.68706414686945   -0.527202862365669         -0.5          0.158301176624629 ⎤
⎢                                                                               ⎥
⎢-0.396676670145617   0.30438071450436   -0.866025403784439  -0.0997321648243623⎥
⎢                                                                               ⎥
⎢0.608761429008721   0.793353340291235           0           0.0529701943328897 ⎥
⎢                                                                               ⎥
⎣        0                   0                   0                   1.0        ⎦


⎡-0.68706414686945          -0.5         -0.527202862365669  0.163414517186714⎤
⎢                                                                             ⎥
⎢0.396676670145617   -0.866025403784439   0.30438071450436   -0.10268435337434⎥
⎢                                                                             ⎥
⎢-0.608761429008721          0           0.793353340291235   0.045275460285405⎥
⎢                                                                             ⎥
⎣        0                   0                   0                  1.0       ⎦


⎡ 0.68706414686945          0.5         0.527202862365669  -0.163414517186714⎤
⎢                                                                            ⎥
⎢-0.396676670145617  0.866025403784439  -0.30438071450436   0.10268435337434 ⎥
⎢                                                                            ⎥
⎢-0.608761429008721          0          0.793353340291235  0.043275460285405 ⎥
⎢                                                                            ⎥
⎣        0                   0                  0                 1.0        ⎦


'Jacobian for the same sets of joint coordinates: '

⎡ [[-0.0126522698572975], [[-0.0995520289235174], [[-0.434283239265684] , [[-0.606879501547702],  [[0.124227194053708] ⎤
⎢  [-0.0219143742239115]   [-0.159966580670287]    [-0.763370459257677]     [0.175167242299632]    [0.197586781712969] ⎥
⎢ [-0.00721999999999999]   [0.00364682790425405]   [0.00457571394406447]    [0.799081351408138]   [-0.0114560222338054]⎥
⎢  [-0.866025403784439]     [0.437430139655675]     [0.548848270915586]     [0.687064146869450]   [-0.687064146869450] ⎥
⎢   [0.500000000000000]    [-0.252550408881859]    [-0.316877696957374]    [-0.396676670145617]    [0.396676670145617] ⎥
⎣          [0]]            [0.863060347770897]]    [-0.773533516199500]]   [0.608761429008721]]   [-0.608761429008721]]⎦


TypeError: unsupported operand type(s) for @: 'list' and 'list'

In [2]:
###### PYTHON INDEXING #######
import numpy as np

x = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9], [10,11,12,13,14]])

# Element indexing is 0-based
print("\n x matrix is \n", x)
print("\n element at line 1, column 3, is ", x[1, 3])

# Note that if one indexes a multidimensional array with fewer indices than dimensions,
# one gets a subdimensional array. For example:
print("\n element 0 of matrix x is \n ",x[0])

# The basic slice syntax is i:j where i is the starting index, j is the stopping index.
# Assume n is the number of elements in the dimension being sliced. 
# Then, if i is not given it defaults to 0 for k > 0 and n - 1 for k < 0 . 

print("\n Line 0, elements from column 3 onwards are \n ",x[0:1,3:])

print("\n Elements from lines 0 to 1, columns 2 to 3 \n", x[0:2,2:4])

###### USEFUL METHODS #######
# Calculating a cross product
x_arr = np.array([[1,2,3]])
y_arr = np.array([[4,5,6]])

c1 = np.cross(x_arr, y_arr)

print("\n c1: \n", c1, "with shape ", c1.shape)

# reshaping
c2 = c1.reshape((3, 1))
print("\n c2 \n", c2, " with shape ", c2.shape)

# transposing
c3 = c1.T

# concatenating vectors
print("\n c3 and c3 concatenated by line \n", np.concatenate((c3, c3), axis=0))
print("\n c3 and c3 concatenated by column \n", np.concatenate((c3, c3), axis=1))


 x matrix is 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

 element at line 1, column 3, is  8

 element 0 of matrix x is 
  [0 1 2 3 4]

 Line 0, elements from column 3 onwards are 
  [[3 4]]

 Elements from lines 0 to 1, columns 2 to 3 
 [[2 3]
 [7 8]]

 c1: 
 [[-3  6 -3]] with shape  (1, 3)

 c2 
 [[-3]
 [ 6]
 [-3]]  with shape  (3, 1)

 c3 and c3 concatenated by line 
 [[-3]
 [ 6]
 [-3]
 [-3]
 [ 6]
 [-3]]

 c3 and c3 concatenated by column 
 [[-3 -3]
 [ 6  6]
 [-3 -3]]


# Extra exercises (just for your satisfaction)
    a. Using the cell below, give different velocity arguments in different scenarios and observe the robot's behaviour.
    b. Using the cell at the end, place the robot in a specific configuration (using new pose option) and, using the interact, visually check for each of the axes the possible instantaneous linear and angular velocities (choosing one joint at a time).

In [ ]:
## extra exercise point a  ##
from al5d_control import *
from ipywidgets import interact, fixed

rrob = AL5DControl()
interact(rrob.robot_control, q0=(-90,90), q1=(-90,90), q2=(-90,90), q3=(-90,90), q4=(-90,90), gripper=(-90,90), dq0=(9,90),dq1=(9,90),dq2=(9,90),dq3=(9,90), dq4=(9,90), vel=fixed(True)) 

In [ ]:
## extra exercise point b  ##
from al5d_control import *
from ipywidgets import interact_manual

rrob = AL5DControl()
interact_manual(rrob.inst_AL5D_velocities, q0=(-90,90),q1=(-90,90),q2=(-90,90),q3=(-90,90),q4=(-90,90), joint = ['new pose','q0', 'q1', 'q2', 'q3','q4']) 